### ISSUE TITLE
Invalid IPv6 addresses

### ISSUE THREAD

**Issue by ignisf** [realizelol/torblocklist#1]
Hi,

https://github.com/realizelol/torblocklist/blob/6f40aedd8ab978665e2069bcfad48bc18486eec2/exits-ipv6.txt#L21
https://github.com/realizelol/torblocklist/blob/6f40aedd8ab978665e2069bcfad48bc18486eec2/exits-ipv6.txt#L504

full list:

```
2a0b:f4c2
2a04:52c0:101:46a
2001:41d0:800:1f70
2402:1f00:8000:239
2602:2e6:0:4
2605:6400:30:efba:dead
2605:6400:30:f44f:1
2605:6400:30:f174
2605:6400:30:f174:42:42
2605:6400:30:f174:cafe
2607:5300:61:785
2607:5300:203:b45b
```

**Comment by realizelol** [comment]
Hi,

thanks a lot this must be all lines containing a double colon at the end of the address (IPv6 meaning -> :0:0)
This has been fixed by commits:
https://github.com/realizelol/torblocklist/commit/f1fb0a68bdf6846485f6b233af1130fd58056e39
+
https://github.com/realizelol/torblocklist/commit/4e107df8af951f22dbd05300b60ac96a9409e051

result:
https://github.com/realizelol/torblocklist/commit/e92a248ef459b21ccf048ea1405d92f40264d0db
